import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://turbosms.in.ua/api/Turbo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Auth", action = "http://turbosms.in.ua/api/Turbo/Auth")
    @WebResult(name = "AuthResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    @RequestWrapper(localName = "Auth", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.Auth")
    @ResponseWrapper(localName = "AuthResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.AuthResponse")
    public String auth(
        @WebParam(name = "login", targetNamespace = "http://turbosms.in.ua/api/Turbo")
        String login,
        @WebParam(name = "password", targetNamespace = "http://turbosms.in.ua/api/Turbo")
        String password);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCreditBalance", action = "http://turbosms.in.ua/api/Turbo/GetCreditBalance")
    @WebResult(name = "GetCreditBalanceResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    @RequestWrapper(localName = "GetCreditBalance", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.GetCreditBalance")
    @ResponseWrapper(localName = "GetCreditBalanceResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.GetCreditBalanceResponse")
    public String getCreditBalance();

    /**
     * 
     * @param sender
     * @param destination
     * @param wappush
     * @param text
     * @return
     *     returns ua.in.turbosms.api.turbo.ArrayOfString
     */
    @WebMethod(operationName = "SendSMS", action = "http://turbosms.in.ua/api/Turbo/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.SendSMSResponse")
    public ArrayOfString sendSMS(
        @WebParam(name = "sender", targetNamespace = "http://turbosms.in.ua/api/Turbo")
        String sender,
        @WebParam(name = "destination", targetNamespace = "http://turbosms.in.ua/api/Turbo")
        String destination,
        @WebParam(name = "text", targetNamespace = "http://turbosms.in.ua/api/Turbo")
        String text,
        @WebParam(name = "wappush", targetNamespace = "http://turbosms.in.ua/api/Turbo")
        String wappush);

    /**
     * 
     * @return
     *     returns ua.in.turbosms.api.turbo.ArrayOfString
     */
    @WebMethod(operationName = "GetNewMessages", action = "http://turbosms.in.ua/api/Turbo/GetNewMessages")
    @WebResult(name = "GetNewMessagesResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    @RequestWrapper(localName = "GetNewMessages", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.GetNewMessages")
    @ResponseWrapper(localName = "GetNewMessagesResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.GetNewMessagesResponse")
    public ArrayOfString getNewMessages();

    /**
     * 
     * @param messageId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMessageStatus", action = "http://turbosms.in.ua/api/Turbo/GetMessageStatus")
    @WebResult(name = "GetMessageStatusResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    @RequestWrapper(localName = "GetMessageStatus", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.GetMessageStatus")
    @ResponseWrapper(localName = "GetMessageStatusResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.in.turbosms.api.turbo.GetMessageStatusResponse")
    public String getMessageStatus(
        @WebParam(name = "MessageId", targetNamespace = "http://turbosms.in.ua/api/Turbo")
        String messageId);

}
